name: Run MonkeOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: chmod everything
      run: chmod +x *.sh
    - name: Build everything pt one
      run: ./scripts/toolchain/toolchain.sh
    - name: cd everything pt one
      run: cd ../../
    - name: cd everything pt two
      run: cd src
    - name: make everything
      run: make
    - name: Deny everything
      run: echo Deny everything
